/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser;

import lexer.*;
import node.*;
import analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AAstart1Start */
		    {
			ArrayList<Object> list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce AAstart2Start */
		    {
			ArrayList<Object> list = new1();
			push(goTo(0), list, false);
		    }
		    break;
                    case 2: /* reduce AAstart3Start */
		    {
			ArrayList<Object> list = new2();
			push(goTo(0), list, false);
		    }
		    break;
                    case 3: /* reduce AAstart4Start */
		    {
			ArrayList<Object> list = new3();
			push(goTo(0), list, false);
		    }
		    break;
                    case 4: /* reduce ASingleDeclarations */
		    {
			ArrayList<Object> list = new4();
			push(goTo(1), list, false);
		    }
		    break;
                    case 5: /* reduce AIfThenStatementStatement */
		    {
			ArrayList<Object> list = new5();
			push(goTo(2), list, false);
		    }
		    break;
                    case 6: /* reduce AIfThenElseStatementStatement */
		    {
			ArrayList<Object> list = new6();
			push(goTo(2), list, false);
		    }
		    break;
                    case 7: /* reduce AWhileStatement */
		    {
			ArrayList<Object> list = new7();
			push(goTo(2), list, false);
		    }
		    break;
                    case 8: /* reduce AAssignStatement */
		    {
			ArrayList<Object> list = new8();
			push(goTo(2), list, false);
		    }
		    break;
                    case 9: /* reduce APrintStatement */
		    {
			ArrayList<Object> list = new9();
			push(goTo(2), list, false);
		    }
		    break;
                    case 10: /* reduce ANestedStatement */
		    {
			ArrayList<Object> list = new10();
			push(goTo(2), list, false);
		    }
		    break;
                    case 11: /* reduce ABreakStatement */
		    {
			ArrayList<Object> list = new11();
			push(goTo(2), list, false);
		    }
		    break;
                    case 12: /* reduce AStatement */
		    {
			ArrayList<Object> list = new12();
			push(goTo(2), list, false);
		    }
		    break;
                    case 13: /* reduce APrint */
		    {
			ArrayList<Object> list = new13();
			push(goTo(3), list, false);
		    }
		    break;
                    case 14: /* reduce AAssignment */
		    {
			ArrayList<Object> list = new14();
			push(goTo(4), list, false);
		    }
		    break;
                    case 15: /* reduce ABooleanType */
		    {
			ArrayList<Object> list = new15();
			push(goTo(5), list, false);
		    }
		    break;
                    case 16: /* reduce AIntegerType */
		    {
			ArrayList<Object> list = new16();
			push(goTo(5), list, false);
		    }
		    break;
                    case 17: /* reduce AComparisionExpr */
		    {
			ArrayList<Object> list = new17();
			push(goTo(6), list, false);
		    }
		    break;
                    case 18: /* reduce AExpr */
		    {
			ArrayList<Object> list = new18();
			push(goTo(6), list, false);
		    }
		    break;
                    case 19: /* reduce APlusExpr2 */
		    {
			ArrayList<Object> list = new19();
			push(goTo(7), list, false);
		    }
		    break;
                    case 20: /* reduce AMinusExpr2 */
		    {
			ArrayList<Object> list = new20();
			push(goTo(7), list, false);
		    }
		    break;
                    case 21: /* reduce AOrExpr2 */
		    {
			ArrayList<Object> list = new21();
			push(goTo(7), list, false);
		    }
		    break;
                    case 22: /* reduce AXorExpr2 */
		    {
			ArrayList<Object> list = new22();
			push(goTo(7), list, false);
		    }
		    break;
                    case 23: /* reduce AExpr2 */
		    {
			ArrayList<Object> list = new23();
			push(goTo(7), list, false);
		    }
		    break;
                    case 24: /* reduce AModExpr3 */
		    {
			ArrayList<Object> list = new24();
			push(goTo(8), list, false);
		    }
		    break;
                    case 25: /* reduce AMultExpr3 */
		    {
			ArrayList<Object> list = new25();
			push(goTo(8), list, false);
		    }
		    break;
                    case 26: /* reduce ADivExpr3 */
		    {
			ArrayList<Object> list = new26();
			push(goTo(8), list, false);
		    }
		    break;
                    case 27: /* reduce AAndExpr3 */
		    {
			ArrayList<Object> list = new27();
			push(goTo(8), list, false);
		    }
		    break;
                    case 28: /* reduce AExpr3 */
		    {
			ArrayList<Object> list = new28();
			push(goTo(8), list, false);
		    }
		    break;
                    case 29: /* reduce ANotExpr4 */
		    {
			ArrayList<Object> list = new29();
			push(goTo(9), list, false);
		    }
		    break;
                    case 30: /* reduce ANumberExpr4 */
		    {
			ArrayList<Object> list = new30();
			push(goTo(9), list, false);
		    }
		    break;
                    case 31: /* reduce AIdentifierExpr4 */
		    {
			ArrayList<Object> list = new31();
			push(goTo(9), list, false);
		    }
		    break;
                    case 32: /* reduce ATrueExpr4 */
		    {
			ArrayList<Object> list = new32();
			push(goTo(9), list, false);
		    }
		    break;
                    case 33: /* reduce AFalseExpr4 */
		    {
			ArrayList<Object> list = new33();
			push(goTo(9), list, false);
		    }
		    break;
                    case 34: /* reduce AGtComparision */
		    {
			ArrayList<Object> list = new34();
			push(goTo(10), list, false);
		    }
		    break;
                    case 35: /* reduce AGeComparision */
		    {
			ArrayList<Object> list = new35();
			push(goTo(10), list, false);
		    }
		    break;
                    case 36: /* reduce ALtComparision */
		    {
			ArrayList<Object> list = new36();
			push(goTo(10), list, false);
		    }
		    break;
                    case 37: /* reduce ALeComparision */
		    {
			ArrayList<Object> list = new37();
			push(goTo(10), list, false);
		    }
		    break;
                    case 38: /* reduce ANeComparision */
		    {
			ArrayList<Object> list = new38();
			push(goTo(10), list, false);
		    }
		    break;
                    case 39: /* reduce AEqComparision */
		    {
			ArrayList<Object> list = new39();
			push(goTo(10), list, false);
		    }
		    break;
                    case 40: /* reduce AIfThenStatement */
		    {
			ArrayList<Object> list = new40();
			push(goTo(11), list, false);
		    }
		    break;
                    case 41: /* reduce AIfThenElseStatement */
		    {
			ArrayList<Object> list = new41();
			push(goTo(12), list, false);
		    }
		    break;
                    case 42: /* reduce AIfThenElseStatementNoShortIf */
		    {
			ArrayList<Object> list = new42();
			push(goTo(13), list, false);
		    }
		    break;
                    case 43: /* reduce AIfStatementNoShortIf */
		    {
			ArrayList<Object> list = new43();
			push(goTo(14), list, false);
		    }
		    break;
                    case 44: /* reduce AWhileStatementNoShortIf */
		    {
			ArrayList<Object> list = new44();
			push(goTo(14), list, false);
		    }
		    break;
                    case 45: /* reduce AWhileWhileStatementNoShortIf */
		    {
			ArrayList<Object> list = new45();
			push(goTo(15), list, false);
		    }
		    break;
                    case 46: /* reduce AWhileWhileStatement */
		    {
			ArrayList<Object> list = new46();
			push(goTo(16), list, false);
		    }
		    break;
                    case 47: /* reduce ATerminal$Declarations */
		    {
			ArrayList<Object> list = new47();
			push(goTo(17), list, true);
		    }
		    break;
                    case 48: /* reduce ANonTerminal$Declarations */
		    {
			ArrayList<Object> list = new48();
			push(goTo(17), list, true);
		    }
		    break;
                    case 49: /* reduce ATerminal$Statement */
		    {
			ArrayList<Object> list = new49();
			push(goTo(18), list, true);
		    }
		    break;
                    case 50: /* reduce ANonTerminal$Statement */
		    {
			ArrayList<Object> list = new50();
			push(goTo(18), list, true);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PStart node1 = (PStart) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AAstart1Start */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStart pstartNode1;
        {
            // Block
        TProgram tprogramNode2;
        TIdentifier tidentifierNode3;
        TSemikolon tsemikolonNode4;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        LinkedList<Object> listNode6 = new LinkedList<Object>();
        TProgramend tprogramendNode7;
        tprogramNode2 = (TProgram)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);
        tsemikolonNode4 = (TSemikolon)nodeArrayList3.get(0);
        {
            // Block
        }
        {
            // Block
        }
        tprogramendNode7 = (TProgramend)nodeArrayList4.get(0);

        pstartNode1 = new AStart(tprogramNode2, tidentifierNode3, tsemikolonNode4, listNode5, listNode6, tprogramendNode7);
        }
	nodeList.add(pstartNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AAstart2Start */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStart pstartNode1;
        {
            // Block
        TProgram tprogramNode2;
        TIdentifier tidentifierNode3;
        TSemikolon tsemikolonNode4;
        LinkedList<Object> listNode6 = new LinkedList<Object>();
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        TProgramend tprogramendNode8;
        tprogramNode2 = (TProgram)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);
        tsemikolonNode4 = (TSemikolon)nodeArrayList3.get(0);
        {
            // Block
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        listNode5 = (LinkedList)nodeArrayList4.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }
        {
            // Block
        }
        tprogramendNode8 = (TProgramend)nodeArrayList5.get(0);

        pstartNode1 = new AStart(tprogramNode2, tidentifierNode3, tsemikolonNode4, listNode6, listNode7, tprogramendNode8);
        }
	nodeList.add(pstartNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AAstart3Start */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStart pstartNode1;
        {
            // Block
        TProgram tprogramNode2;
        TIdentifier tidentifierNode3;
        TSemikolon tsemikolonNode4;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        TProgramend tprogramendNode8;
        tprogramNode2 = (TProgram)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);
        tsemikolonNode4 = (TSemikolon)nodeArrayList3.get(0);
        {
            // Block
        }
        {
            // Block
        LinkedList<Object> listNode6 = new LinkedList<Object>();
        listNode6 = (LinkedList)nodeArrayList4.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
        tprogramendNode8 = (TProgramend)nodeArrayList5.get(0);

        pstartNode1 = new AStart(tprogramNode2, tidentifierNode3, tsemikolonNode4, listNode5, listNode7, tprogramendNode8);
        }
	nodeList.add(pstartNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AAstart4Start */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStart pstartNode1;
        {
            // Block
        TProgram tprogramNode2;
        TIdentifier tidentifierNode3;
        TSemikolon tsemikolonNode4;
        LinkedList<Object> listNode6 = new LinkedList<Object>();
        LinkedList<Object> listNode8 = new LinkedList<Object>();
        TProgramend tprogramendNode9;
        tprogramNode2 = (TProgram)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);
        tsemikolonNode4 = (TSemikolon)nodeArrayList3.get(0);
        {
            // Block
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        listNode5 = (LinkedList)nodeArrayList4.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }
        {
            // Block
        LinkedList<Object> listNode7 = new LinkedList<Object>();
        listNode7 = (LinkedList)nodeArrayList5.get(0);
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
        tprogramendNode9 = (TProgramend)nodeArrayList6.get(0);

        pstartNode1 = new AStart(tprogramNode2, tidentifierNode3, tsemikolonNode4, listNode6, listNode8, tprogramendNode9);
        }
	nodeList.add(pstartNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce ASingleDeclarations */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDeclarations pdeclarationsNode1;
        {
            // Block
        TVar tvarNode2;
        TIdentifier tidentifierNode3;
        TColon tcolonNode4;
        PType ptypeNode5;
        TSemikolon tsemikolonNode6;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);
        tcolonNode4 = (TColon)nodeArrayList3.get(0);
        ptypeNode5 = (PType)nodeArrayList4.get(0);
        tsemikolonNode6 = (TSemikolon)nodeArrayList5.get(0);

        pdeclarationsNode1 = new ASingleDeclarations(tvarNode2, tidentifierNode3, tcolonNode4, ptypeNode5, tsemikolonNode6);
        }
	nodeList.add(pdeclarationsNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce AIfThenStatementStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PIfThenStatement pifthenstatementNode2;
        pifthenstatementNode2 = (PIfThenStatement)nodeArrayList1.get(0);

        pstatementNode1 = new AIfThenStatementStatement(pifthenstatementNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AIfThenElseStatementStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PIfThenElseStatement pifthenelsestatementNode2;
        pifthenelsestatementNode2 = (PIfThenElseStatement)nodeArrayList1.get(0);

        pstatementNode1 = new AIfThenElseStatementStatement(pifthenelsestatementNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AWhileStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PWhileStatement pwhilestatementNode2;
        pwhilestatementNode2 = (PWhileStatement)nodeArrayList1.get(0);

        pstatementNode1 = new AWhileStatement(pwhilestatementNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AAssignStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PAssignment passignmentNode2;
        passignmentNode2 = (PAssignment)nodeArrayList1.get(0);

        pstatementNode1 = new AAssignStatement(passignmentNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce APrintStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PPrint pprintNode2;
        pprintNode2 = (PPrint)nodeArrayList1.get(0);

        pstatementNode1 = new APrintStatement(pprintNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ANestedStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TBegin tbeginNode2;
        PStatement pstatementNode3;
        TEnd tendNode4;
        tbeginNode2 = (TBegin)nodeArrayList1.get(0);
        pstatementNode3 = (PStatement)nodeArrayList2.get(0);
        tendNode4 = (TEnd)nodeArrayList3.get(0);

        pstatementNode1 = new ANestedStatement(tbeginNode2, pstatementNode3, tendNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce ABreakStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TBreak tbreakNode2;
        tbreakNode2 = (TBreak)nodeArrayList1.get(0);

        pstatementNode1 = new ABreakStatement(tbreakNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce AStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TSemikolon tsemikolonNode2;
        tsemikolonNode2 = (TSemikolon)nodeArrayList1.get(0);

        pstatementNode1 = new AStatement(tsemikolonNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce APrint */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrint pprintNode1;
        {
            // Block
        TWriteln twritelnNode2;
        TLPar tlparNode3;
        PExpr pexprNode4;
        TRPar trparNode5;
        twritelnNode2 = (TWriteln)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pexprNode4 = (PExpr)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);

        pprintNode1 = new APrint(twritelnNode2, tlparNode3, pexprNode4, trparNode5);
        }
	nodeList.add(pprintNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce AAssignment */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAssignment passignmentNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        TAssign tassignNode3;
        PExpr pexprNode4;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        tassignNode3 = (TAssign)nodeArrayList2.get(0);
        pexprNode4 = (PExpr)nodeArrayList3.get(0);

        passignmentNode1 = new AAssignment(tidentifierNode2, tassignNode3, pexprNode4);
        }
	nodeList.add(passignmentNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce ABooleanType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TBoolean tbooleanNode2;
        tbooleanNode2 = (TBoolean)nodeArrayList1.get(0);

        ptypeNode1 = new ABooleanType(tbooleanNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce AIntegerType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TInteger tintegerNode2;
        tintegerNode2 = (TInteger)nodeArrayList1.get(0);

        ptypeNode1 = new AIntegerType(tintegerNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AComparisionExpr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PExpr pexprNode2;
        PComparision pcomparisionNode3;
        PExpr2 pexpr2Node4;
        pexprNode2 = (PExpr)nodeArrayList1.get(0);
        pcomparisionNode3 = (PComparision)nodeArrayList2.get(0);
        pexpr2Node4 = (PExpr2)nodeArrayList3.get(0);

        pexprNode1 = new AComparisionExpr(pexprNode2, pcomparisionNode3, pexpr2Node4);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce AExpr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr pexprNode1;
        {
            // Block
        PExpr2 pexpr2Node2;
        pexpr2Node2 = (PExpr2)nodeArrayList1.get(0);

        pexprNode1 = new AExpr(pexpr2Node2);
        }
	nodeList.add(pexprNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce APlusExpr2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr2 pexpr2Node1;
        {
            // Block
        PExpr2 pexpr2Node2;
        TPlus tplusNode3;
        PExpr3 pexpr3Node4;
        pexpr2Node2 = (PExpr2)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pexpr3Node4 = (PExpr3)nodeArrayList3.get(0);

        pexpr2Node1 = new APlusExpr2(pexpr2Node2, tplusNode3, pexpr3Node4);
        }
	nodeList.add(pexpr2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce AMinusExpr2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr2 pexpr2Node1;
        {
            // Block
        PExpr2 pexpr2Node2;
        TMinus tminusNode3;
        PExpr3 pexpr3Node4;
        pexpr2Node2 = (PExpr2)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        pexpr3Node4 = (PExpr3)nodeArrayList3.get(0);

        pexpr2Node1 = new AMinusExpr2(pexpr2Node2, tminusNode3, pexpr3Node4);
        }
	nodeList.add(pexpr2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AOrExpr2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr2 pexpr2Node1;
        {
            // Block
        PExpr2 pexpr2Node2;
        TOr torNode3;
        PExpr3 pexpr3Node4;
        pexpr2Node2 = (PExpr2)nodeArrayList1.get(0);
        torNode3 = (TOr)nodeArrayList2.get(0);
        pexpr3Node4 = (PExpr3)nodeArrayList3.get(0);

        pexpr2Node1 = new AOrExpr2(pexpr2Node2, torNode3, pexpr3Node4);
        }
	nodeList.add(pexpr2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AXorExpr2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr2 pexpr2Node1;
        {
            // Block
        PExpr2 pexpr2Node2;
        TXor txorNode3;
        PExpr3 pexpr3Node4;
        pexpr2Node2 = (PExpr2)nodeArrayList1.get(0);
        txorNode3 = (TXor)nodeArrayList2.get(0);
        pexpr3Node4 = (PExpr3)nodeArrayList3.get(0);

        pexpr2Node1 = new AXorExpr2(pexpr2Node2, txorNode3, pexpr3Node4);
        }
	nodeList.add(pexpr2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce AExpr2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr2 pexpr2Node1;
        {
            // Block
        PExpr3 pexpr3Node2;
        pexpr3Node2 = (PExpr3)nodeArrayList1.get(0);

        pexpr2Node1 = new AExpr2(pexpr3Node2);
        }
	nodeList.add(pexpr2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce AModExpr3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr3 pexpr3Node1;
        {
            // Block
        PExpr3 pexpr3Node2;
        TMod tmodNode3;
        PExpr4 pexpr4Node4;
        pexpr3Node2 = (PExpr3)nodeArrayList1.get(0);
        tmodNode3 = (TMod)nodeArrayList2.get(0);
        pexpr4Node4 = (PExpr4)nodeArrayList3.get(0);

        pexpr3Node1 = new AModExpr3(pexpr3Node2, tmodNode3, pexpr4Node4);
        }
	nodeList.add(pexpr3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce AMultExpr3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr3 pexpr3Node1;
        {
            // Block
        PExpr3 pexpr3Node2;
        TMult tmultNode3;
        PExpr4 pexpr4Node4;
        pexpr3Node2 = (PExpr3)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        pexpr4Node4 = (PExpr4)nodeArrayList3.get(0);

        pexpr3Node1 = new AMultExpr3(pexpr3Node2, tmultNode3, pexpr4Node4);
        }
	nodeList.add(pexpr3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce ADivExpr3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr3 pexpr3Node1;
        {
            // Block
        PExpr3 pexpr3Node2;
        TDiv tdivNode3;
        PExpr4 pexpr4Node4;
        pexpr3Node2 = (PExpr3)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        pexpr4Node4 = (PExpr4)nodeArrayList3.get(0);

        pexpr3Node1 = new ADivExpr3(pexpr3Node2, tdivNode3, pexpr4Node4);
        }
	nodeList.add(pexpr3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AAndExpr3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr3 pexpr3Node1;
        {
            // Block
        PExpr3 pexpr3Node2;
        TAnd tandNode3;
        PExpr4 pexpr4Node4;
        pexpr3Node2 = (PExpr3)nodeArrayList1.get(0);
        tandNode3 = (TAnd)nodeArrayList2.get(0);
        pexpr4Node4 = (PExpr4)nodeArrayList3.get(0);

        pexpr3Node1 = new AAndExpr3(pexpr3Node2, tandNode3, pexpr4Node4);
        }
	nodeList.add(pexpr3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce AExpr3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr3 pexpr3Node1;
        {
            // Block
        PExpr4 pexpr4Node2;
        pexpr4Node2 = (PExpr4)nodeArrayList1.get(0);

        pexpr3Node1 = new AExpr3(pexpr4Node2);
        }
	nodeList.add(pexpr3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce ANotExpr4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr4 pexpr4Node1;
        {
            // Block
        TNot tnotNode2;
        PExpr4 pexpr4Node3;
        tnotNode2 = (TNot)nodeArrayList1.get(0);
        pexpr4Node3 = (PExpr4)nodeArrayList2.get(0);

        pexpr4Node1 = new ANotExpr4(tnotNode2, pexpr4Node3);
        }
	nodeList.add(pexpr4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce ANumberExpr4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr4 pexpr4Node1;
        {
            // Block
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pexpr4Node1 = new ANumberExpr4(tnumberNode2);
        }
	nodeList.add(pexpr4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce AIdentifierExpr4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr4 pexpr4Node1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);

        pexpr4Node1 = new AIdentifierExpr4(tidentifierNode2);
        }
	nodeList.add(pexpr4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce ATrueExpr4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr4 pexpr4Node1;
        {
            // Block
        TTrue ttrueNode2;
        ttrueNode2 = (TTrue)nodeArrayList1.get(0);

        pexpr4Node1 = new ATrueExpr4(ttrueNode2);
        }
	nodeList.add(pexpr4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce AFalseExpr4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExpr4 pexpr4Node1;
        {
            // Block
        TFalse tfalseNode2;
        tfalseNode2 = (TFalse)nodeArrayList1.get(0);

        pexpr4Node1 = new AFalseExpr4(tfalseNode2);
        }
	nodeList.add(pexpr4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AGtComparision */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PComparision pcomparisionNode1;
        {
            // Block
        TGt tgtNode2;
        tgtNode2 = (TGt)nodeArrayList1.get(0);

        pcomparisionNode1 = new AGtComparision(tgtNode2);
        }
	nodeList.add(pcomparisionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AGeComparision */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PComparision pcomparisionNode1;
        {
            // Block
        TGe tgeNode2;
        tgeNode2 = (TGe)nodeArrayList1.get(0);

        pcomparisionNode1 = new AGeComparision(tgeNode2);
        }
	nodeList.add(pcomparisionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce ALtComparision */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PComparision pcomparisionNode1;
        {
            // Block
        TLt tltNode2;
        tltNode2 = (TLt)nodeArrayList1.get(0);

        pcomparisionNode1 = new ALtComparision(tltNode2);
        }
	nodeList.add(pcomparisionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce ALeComparision */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PComparision pcomparisionNode1;
        {
            // Block
        TLe tleNode2;
        tleNode2 = (TLe)nodeArrayList1.get(0);

        pcomparisionNode1 = new ALeComparision(tleNode2);
        }
	nodeList.add(pcomparisionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce ANeComparision */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PComparision pcomparisionNode1;
        {
            // Block
        TNe tneNode2;
        tneNode2 = (TNe)nodeArrayList1.get(0);

        pcomparisionNode1 = new ANeComparision(tneNode2);
        }
	nodeList.add(pcomparisionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce AEqComparision */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PComparision pcomparisionNode1;
        {
            // Block
        TEq teqNode2;
        teqNode2 = (TEq)nodeArrayList1.get(0);

        pcomparisionNode1 = new AEqComparision(teqNode2);
        }
	nodeList.add(pcomparisionNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce AIfThenStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIfThenStatement pifthenstatementNode1;
        {
            // Block
        TIf tifNode2;
        PExpr pexprNode3;
        TThen tthenNode4;
        PStatement pstatementNode5;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        pexprNode3 = (PExpr)nodeArrayList2.get(0);
        tthenNode4 = (TThen)nodeArrayList3.get(0);
        pstatementNode5 = (PStatement)nodeArrayList4.get(0);

        pifthenstatementNode1 = new AIfThenStatement(tifNode2, pexprNode3, tthenNode4, pstatementNode5);
        }
	nodeList.add(pifthenstatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce AIfThenElseStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIfThenElseStatement pifthenelsestatementNode1;
        {
            // Block
        TIf tifNode2;
        PExpr pexprNode3;
        TThen tthenNode4;
        PStatementNoShortIf pstatementnoshortifNode5;
        TElse telseNode6;
        PStatement pstatementNode7;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        pexprNode3 = (PExpr)nodeArrayList2.get(0);
        tthenNode4 = (TThen)nodeArrayList3.get(0);
        pstatementnoshortifNode5 = (PStatementNoShortIf)nodeArrayList4.get(0);
        telseNode6 = (TElse)nodeArrayList5.get(0);
        pstatementNode7 = (PStatement)nodeArrayList6.get(0);

        pifthenelsestatementNode1 = new AIfThenElseStatement(tifNode2, pexprNode3, tthenNode4, pstatementnoshortifNode5, telseNode6, pstatementNode7);
        }
	nodeList.add(pifthenelsestatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce AIfThenElseStatementNoShortIf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIfThenElseStatementNoShortIf pifthenelsestatementnoshortifNode1;
        {
            // Block
        TIf tifNode2;
        PExpr pexprNode3;
        TThen tthenNode4;
        PStatementNoShortIf pstatementnoshortifNode5;
        TElse telseNode6;
        PStatementNoShortIf pstatementnoshortifNode7;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        pexprNode3 = (PExpr)nodeArrayList2.get(0);
        tthenNode4 = (TThen)nodeArrayList3.get(0);
        pstatementnoshortifNode5 = (PStatementNoShortIf)nodeArrayList4.get(0);
        telseNode6 = (TElse)nodeArrayList5.get(0);
        pstatementnoshortifNode7 = (PStatementNoShortIf)nodeArrayList6.get(0);

        pifthenelsestatementnoshortifNode1 = new AIfThenElseStatementNoShortIf(tifNode2, pexprNode3, tthenNode4, pstatementnoshortifNode5, telseNode6, pstatementnoshortifNode7);
        }
	nodeList.add(pifthenelsestatementnoshortifNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce AIfStatementNoShortIf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatementNoShortIf pstatementnoshortifNode1;
        {
            // Block
        PIfThenElseStatementNoShortIf pifthenelsestatementnoshortifNode2;
        pifthenelsestatementnoshortifNode2 = (PIfThenElseStatementNoShortIf)nodeArrayList1.get(0);

        pstatementnoshortifNode1 = new AIfStatementNoShortIf(pifthenelsestatementnoshortifNode2);
        }
	nodeList.add(pstatementnoshortifNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce AWhileStatementNoShortIf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStatementNoShortIf pstatementnoshortifNode1;
        {
            // Block
        PWhileStatementNoShortIf pwhilestatementnoshortifNode2;
        pwhilestatementnoshortifNode2 = (PWhileStatementNoShortIf)nodeArrayList1.get(0);

        pstatementnoshortifNode1 = new AWhileStatementNoShortIf(pwhilestatementnoshortifNode2);
        }
	nodeList.add(pstatementnoshortifNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce AWhileWhileStatementNoShortIf */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PWhileStatementNoShortIf pwhilestatementnoshortifNode1;
        {
            // Block
        TWhile twhileNode2;
        PExpr pexprNode3;
        TDo tdoNode4;
        PStatementNoShortIf pstatementnoshortifNode5;
        twhileNode2 = (TWhile)nodeArrayList1.get(0);
        pexprNode3 = (PExpr)nodeArrayList2.get(0);
        tdoNode4 = (TDo)nodeArrayList3.get(0);
        pstatementnoshortifNode5 = (PStatementNoShortIf)nodeArrayList4.get(0);

        pwhilestatementnoshortifNode1 = new AWhileWhileStatementNoShortIf(twhileNode2, pexprNode3, tdoNode4, pstatementnoshortifNode5);
        }
	nodeList.add(pwhilestatementnoshortifNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce AWhileWhileStatement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PWhileStatement pwhilestatementNode1;
        {
            // Block
        TWhile twhileNode2;
        PExpr pexprNode3;
        TDo tdoNode4;
        PStatement pstatementNode5;
        twhileNode2 = (TWhile)nodeArrayList1.get(0);
        pexprNode3 = (PExpr)nodeArrayList2.get(0);
        tdoNode4 = (TDo)nodeArrayList3.get(0);
        pstatementNode5 = (PStatement)nodeArrayList4.get(0);

        pwhilestatementNode1 = new AWhileWhileStatement(twhileNode2, pexprNode3, tdoNode4, pstatementNode5);
        }
	nodeList.add(pwhilestatementNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce ATerminal$Declarations */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PDeclarations pdeclarationsNode1;
        pdeclarationsNode1 = (PDeclarations)nodeArrayList1.get(0);
	if(pdeclarationsNode1 != null)
	{
	  listNode2.add(pdeclarationsNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce ANonTerminal$Declarations */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PDeclarations pdeclarationsNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pdeclarationsNode2 = (PDeclarations)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pdeclarationsNode2 != null)
	{
	  listNode3.add(pdeclarationsNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce ATerminal$Statement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PStatement pstatementNode1;
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
	if(pstatementNode1 != null)
	{
	  listNode2.add(pstatementNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce ANonTerminal$Statement */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PStatement pstatementNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pstatementNode2 = (PStatement)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pstatementNode2 != null)
	{
	  listNode3.add(pstatementNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {8, SHIFT, 1}, },
			{{-1, ERROR, 1}, {38, SHIFT, 3}, },
			{{-1, ERROR, 2}, {39, ACCEPT, -1}, },
			{{-1, ERROR, 3}, {36, SHIFT, 4}, },
			{{-1, ERROR, 4}, {2, SHIFT, 5}, {5, SHIFT, 6}, {6, SHIFT, 7}, {9, SHIFT, 8}, {12, SHIFT, 9}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, ERROR, 5}, {38, SHIFT, 23}, },
			{{-1, ERROR, 6}, {5, SHIFT, 6}, {9, SHIFT, 8}, {12, SHIFT, 9}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 8}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 9}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 10}, {16, SHIFT, 35}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 12}, },
			{{-1, ERROR, 13}, {4, SHIFT, 36}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 21}, {2, SHIFT, 5}, {5, SHIFT, 6}, {6, SHIFT, 37}, {9, SHIFT, 8}, {12, SHIFT, 9}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, ERROR, 22}, {5, SHIFT, 6}, {6, SHIFT, 40}, {9, SHIFT, 8}, {12, SHIFT, 9}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, ERROR, 23}, {35, SHIFT, 42}, },
			{{-1, ERROR, 24}, {7, SHIFT, 43}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 26}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 30}, {10, SHIFT, 45}, {23, SHIFT, 46}, {24, SHIFT, 47}, {25, SHIFT, 48}, {26, SHIFT, 49}, {27, SHIFT, 50}, {28, SHIFT, 51}, },
			{{-1, REDUCE, 18}, {18, SHIFT, 53}, {19, SHIFT, 54}, {30, SHIFT, 55}, {31, SHIFT, 56}, },
			{{-1, REDUCE, 23}, {20, SHIFT, 57}, {21, SHIFT, 58}, {22, SHIFT, 59}, {29, SHIFT, 60}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 34}, {13, SHIFT, 61}, {23, SHIFT, 46}, {24, SHIFT, 47}, {25, SHIFT, 48}, {26, SHIFT, 49}, {27, SHIFT, 50}, {28, SHIFT, 51}, },
			{{-1, ERROR, 35}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 36}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 48}, },
			{{-1, ERROR, 39}, {5, SHIFT, 6}, {6, SHIFT, 64}, {9, SHIFT, 8}, {12, SHIFT, 9}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 50}, },
			{{-1, ERROR, 42}, {0, SHIFT, 65}, {1, SHIFT, 66}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 45}, {5, SHIFT, 6}, {9, SHIFT, 68}, {12, SHIFT, 69}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 37}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 52}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 53}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 54}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 55}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 56}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 57}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 58}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 59}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 60}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 61}, {5, SHIFT, 6}, {9, SHIFT, 8}, {12, SHIFT, 9}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, ERROR, 62}, {17, SHIFT, 84}, {23, SHIFT, 46}, {24, SHIFT, 47}, {25, SHIFT, 48}, {26, SHIFT, 49}, {27, SHIFT, 50}, {28, SHIFT, 51}, },
			{{-1, REDUCE, 14}, {23, SHIFT, 46}, {24, SHIFT, 47}, {25, SHIFT, 48}, {26, SHIFT, 49}, {27, SHIFT, 50}, {28, SHIFT, 51}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 67}, {36, SHIFT, 85}, },
			{{-1, ERROR, 68}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, ERROR, 69}, {3, SHIFT, 25}, {32, SHIFT, 26}, {33, SHIFT, 27}, {34, SHIFT, 28}, {38, SHIFT, 29}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 43}, },
			{{-1, ERROR, 72}, {11, SHIFT, 88}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 17}, {18, SHIFT, 53}, {19, SHIFT, 54}, {30, SHIFT, 55}, {31, SHIFT, 56}, },
			{{-1, REDUCE, 19}, {20, SHIFT, 57}, {21, SHIFT, 58}, {22, SHIFT, 59}, {29, SHIFT, 60}, },
			{{-1, REDUCE, 20}, {20, SHIFT, 57}, {21, SHIFT, 58}, {22, SHIFT, 59}, {29, SHIFT, 60}, },
			{{-1, REDUCE, 21}, {20, SHIFT, 57}, {21, SHIFT, 58}, {22, SHIFT, 59}, {29, SHIFT, 60}, },
			{{-1, REDUCE, 22}, {20, SHIFT, 57}, {21, SHIFT, 58}, {22, SHIFT, 59}, {29, SHIFT, 60}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 86}, {10, SHIFT, 89}, {23, SHIFT, 46}, {24, SHIFT, 47}, {25, SHIFT, 48}, {26, SHIFT, 49}, {27, SHIFT, 50}, {28, SHIFT, 51}, },
			{{-1, ERROR, 87}, {13, SHIFT, 90}, {23, SHIFT, 46}, {24, SHIFT, 47}, {25, SHIFT, 48}, {26, SHIFT, 49}, {27, SHIFT, 50}, {28, SHIFT, 51}, },
			{{-1, ERROR, 88}, {5, SHIFT, 6}, {9, SHIFT, 8}, {12, SHIFT, 9}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, ERROR, 89}, {5, SHIFT, 6}, {9, SHIFT, 68}, {12, SHIFT, 69}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, ERROR, 90}, {5, SHIFT, 6}, {9, SHIFT, 68}, {12, SHIFT, 69}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, REDUCE, 41}, },
			{{-1, ERROR, 92}, {11, SHIFT, 94}, },
			{{-1, REDUCE, 45}, },
			{{-1, ERROR, 94}, {5, SHIFT, 6}, {9, SHIFT, 68}, {12, SHIFT, 69}, {14, SHIFT, 10}, {15, SHIFT, 11}, {36, SHIFT, 12}, {38, SHIFT, 13}, },
			{{-1, REDUCE, 42}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 14}, {21, 38}, },
			{{-1, 15}, {6, 24}, {22, 41}, {39, 41}, {45, 70}, {61, 83}, {88, 91}, {89, 70}, {90, 83}, {94, 91}, },
			{{-1, 16}, },
			{{-1, 17}, },
			{{-1, 67}, },
			{{-1, 30}, {9, 34}, {35, 62}, {36, 63}, {68, 86}, {69, 87}, },
			{{-1, 31}, {52, 74}, },
			{{-1, 32}, {53, 75}, {54, 76}, {55, 77}, {56, 78}, },
			{{-1, 33}, {26, 44}, {57, 79}, {58, 80}, {59, 81}, {60, 82}, },
			{{-1, 52}, },
			{{-1, 18}, },
			{{-1, 19}, },
			{{-1, 71}, },
			{{-1, 72}, {89, 92}, {90, 93}, {94, 95}, },
			{{-1, 73}, },
			{{-1, 20}, },
			{{-1, 21}, },
			{{-1, 22}, {21, 39}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'program'",
			"expecting: identifier",
			"expecting: EOF",
			"expecting: ';'",
			"expecting: 'var', 'begin', 'end.', 'if', 'while', 'writeln', 'break', ';', identifier",
			"expecting: 'begin', 'if', 'while', 'writeln', 'break', ';', identifier",
			"expecting: number, 'not', 'true', 'false', identifier",
			"expecting: '('",
			"expecting: 'begin', 'end.', 'end', 'if', 'while', 'writeln', 'break', ';', identifier",
			"expecting: ':='",
			"expecting: 'begin', 'end.', 'if', 'while', 'writeln', 'break', ';', identifier",
			"expecting: ':'",
			"expecting: 'end'",
			"expecting: 'begin', 'end.', 'end', 'if', 'then', 'while', 'do', 'writeln', 'break', ')', '+', '-', '*', 'div', 'mod', '=', '<', '>', '<=', '>=', '<>', 'and', 'or', 'xor', ';', identifier",
			"expecting: 'then', '=', '<', '>', '<=', '>=', '<>'",
			"expecting: 'begin', 'end.', 'end', 'if', 'then', 'while', 'do', 'writeln', 'break', ')', '+', '-', '=', '<', '>', '<=', '>=', '<>', 'or', 'xor', ';', identifier",
			"expecting: 'do', '=', '<', '>', '<=', '>=', '<>'",
			"expecting: 'integer', 'boolean'",
			"expecting: ')', '=', '<', '>', '<=', '>=', '<>'",
			"expecting: 'begin', 'end.', 'end', 'if', 'while', 'writeln', 'break', '=', '<', '>', '<=', '>=', '<>', ';', identifier",
			"expecting: 'else'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 1, 5, 2, 6, 6, 7, 8, 8, 9, 4, 10, 8, 8, 8, 8, 8, 4, 10, 11, 12, 13, 6, 13, 13, 13, 14, 15, 13, 13, 16, 6, 6, 2, 4, 10, 2, 10, 17, 8, 13, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 18, 19, 2, 3, 3, 3, 6, 6, 8, 20, 20, 20, 15, 13, 13, 13, 13, 13, 13, 13, 13, 8, 8, 4, 14, 16, 5, 5, 5, 8, 20, 20, 5, 20, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
