/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AArithexprExpr extends PExpr
{
    private PArithexpr _arithexpr_;

    public AArithexprExpr()
    {
        // Constructor
    }

    public AArithexprExpr(
        @SuppressWarnings("hiding") PArithexpr _arithexpr_)
    {
        // Constructor
        setArithexpr(_arithexpr_);

    }

    @Override
    public Object clone()
    {
        return new AArithexprExpr(
            cloneNode(this._arithexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArithexprExpr(this);
    }

    public PArithexpr getArithexpr()
    {
        return this._arithexpr_;
    }

    public void setArithexpr(PArithexpr node)
    {
        if(this._arithexpr_ != null)
        {
            this._arithexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arithexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arithexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arithexpr_ == child)
        {
            this._arithexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arithexpr_ == oldChild)
        {
            setArithexpr((PArithexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
