/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ABoolcomp extends PBoolcomp
{
    private PBoolexpr _boolexpr_;

    public ABoolcomp()
    {
        // Constructor
    }

    public ABoolcomp(
        @SuppressWarnings("hiding") PBoolexpr _boolexpr_)
    {
        // Constructor
        setBoolexpr(_boolexpr_);

    }

    @Override
    public Object clone()
    {
        return new ABoolcomp(
            cloneNode(this._boolexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolcomp(this);
    }

    public PBoolexpr getBoolexpr()
    {
        return this._boolexpr_;
    }

    public void setBoolexpr(PBoolexpr node)
    {
        if(this._boolexpr_ != null)
        {
            this._boolexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolexpr_ == child)
        {
            this._boolexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolexpr_ == oldChild)
        {
            setBoolexpr((PBoolexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
