/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ABoolfactor extends PBoolfactor
{
    private TBoolidentifier _boolidentifier_;

    public ABoolfactor()
    {
        // Constructor
    }

    public ABoolfactor(
        @SuppressWarnings("hiding") TBoolidentifier _boolidentifier_)
    {
        // Constructor
        setBoolidentifier(_boolidentifier_);

    }

    @Override
    public Object clone()
    {
        return new ABoolfactor(
            cloneNode(this._boolidentifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolfactor(this);
    }

    public TBoolidentifier getBoolidentifier()
    {
        return this._boolidentifier_;
    }

    public void setBoolidentifier(TBoolidentifier node)
    {
        if(this._boolidentifier_ != null)
        {
            this._boolidentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolidentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolidentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolidentifier_ == child)
        {
            this._boolidentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolidentifier_ == oldChild)
        {
            setBoolidentifier((TBoolidentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
