/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ABoolexpr extends PBoolexpr
{
    private PBoolterm _boolterm_;

    public ABoolexpr()
    {
        // Constructor
    }

    public ABoolexpr(
        @SuppressWarnings("hiding") PBoolterm _boolterm_)
    {
        // Constructor
        setBoolterm(_boolterm_);

    }

    @Override
    public Object clone()
    {
        return new ABoolexpr(
            cloneNode(this._boolterm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolexpr(this);
    }

    public PBoolterm getBoolterm()
    {
        return this._boolterm_;
    }

    public void setBoolterm(PBoolterm node)
    {
        if(this._boolterm_ != null)
        {
            this._boolterm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolterm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._boolterm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._boolterm_ == child)
        {
            this._boolterm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._boolterm_ == oldChild)
        {
            setBoolterm((PBoolterm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
