/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AComparisionExpr extends PExpr
{
    private PExpr _left_;
    private PComparision _comparision_;
    private PExpr2 _right_;

    public AComparisionExpr()
    {
        // Constructor
    }

    public AComparisionExpr(
        @SuppressWarnings("hiding") PExpr _left_,
        @SuppressWarnings("hiding") PComparision _comparision_,
        @SuppressWarnings("hiding") PExpr2 _right_)
    {
        // Constructor
        setLeft(_left_);

        setComparision(_comparision_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AComparisionExpr(
            cloneNode(this._left_),
            cloneNode(this._comparision_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComparisionExpr(this);
    }

    public PExpr getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExpr node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public PComparision getComparision()
    {
        return this._comparision_;
    }

    public void setComparision(PComparision node)
    {
        if(this._comparision_ != null)
        {
            this._comparision_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comparision_ = node;
    }

    public PExpr2 getRight()
    {
        return this._right_;
    }

    public void setRight(PExpr2 node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._comparision_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._comparision_ == child)
        {
            this._comparision_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExpr) newChild);
            return;
        }

        if(this._comparision_ == oldChild)
        {
            setComparision((PComparision) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExpr2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
