/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIfWhileoperation extends PWhileoperation
{
    private PIfexpr _ifexpr_;

    public AIfWhileoperation()
    {
        // Constructor
    }

    public AIfWhileoperation(
        @SuppressWarnings("hiding") PIfexpr _ifexpr_)
    {
        // Constructor
        setIfexpr(_ifexpr_);

    }

    @Override
    public Object clone()
    {
        return new AIfWhileoperation(
            cloneNode(this._ifexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfWhileoperation(this);
    }

    public PIfexpr getIfexpr()
    {
        return this._ifexpr_;
    }

    public void setIfexpr(PIfexpr node)
    {
        if(this._ifexpr_ != null)
        {
            this._ifexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifexpr_ == child)
        {
            this._ifexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifexpr_ == oldChild)
        {
            setIfexpr((PIfexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
