/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AInstructionWhilenested extends PWhilenested
{
    private PWhileinstructions _left_;
    private TSemikolon _semikolon_;
    private PWhileinstructions _right_;

    public AInstructionWhilenested()
    {
        // Constructor
    }

    public AInstructionWhilenested(
        @SuppressWarnings("hiding") PWhileinstructions _left_,
        @SuppressWarnings("hiding") TSemikolon _semikolon_,
        @SuppressWarnings("hiding") PWhileinstructions _right_)
    {
        // Constructor
        setLeft(_left_);

        setSemikolon(_semikolon_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionWhilenested(
            cloneNode(this._left_),
            cloneNode(this._semikolon_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionWhilenested(this);
    }

    public PWhileinstructions getLeft()
    {
        return this._left_;
    }

    public void setLeft(PWhileinstructions node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TSemikolon getSemikolon()
    {
        return this._semikolon_;
    }

    public void setSemikolon(TSemikolon node)
    {
        if(this._semikolon_ != null)
        {
            this._semikolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semikolon_ = node;
    }

    public PWhileinstructions getRight()
    {
        return this._right_;
    }

    public void setRight(PWhileinstructions node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._semikolon_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._semikolon_ == child)
        {
            this._semikolon_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PWhileinstructions) newChild);
            return;
        }

        if(this._semikolon_ == oldChild)
        {
            setSemikolon((TSemikolon) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PWhileinstructions) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
