/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMatchedIfexpr extends PIfexpr
{
    private PFmatchedStmt _fmatchedStmt_;

    public AMatchedIfexpr()
    {
        // Constructor
    }

    public AMatchedIfexpr(
        @SuppressWarnings("hiding") PFmatchedStmt _fmatchedStmt_)
    {
        // Constructor
        setFmatchedStmt(_fmatchedStmt_);

    }

    @Override
    public Object clone()
    {
        return new AMatchedIfexpr(
            cloneNode(this._fmatchedStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMatchedIfexpr(this);
    }

    public PFmatchedStmt getFmatchedStmt()
    {
        return this._fmatchedStmt_;
    }

    public void setFmatchedStmt(PFmatchedStmt node)
    {
        if(this._fmatchedStmt_ != null)
        {
            this._fmatchedStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fmatchedStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fmatchedStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fmatchedStmt_ == child)
        {
            this._fmatchedStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fmatchedStmt_ == oldChild)
        {
            setFmatchedStmt((PFmatchedStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
