/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotExpression4 extends PExpression4
{
    private TNot _not_;
    private PExpression4 _expression4_;

    public ANotExpression4()
    {
        // Constructor
    }

    public ANotExpression4(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PExpression4 _expression4_)
    {
        // Constructor
        setNot(_not_);

        setExpression4(_expression4_);

    }

    @Override
    public Object clone()
    {
        return new ANotExpression4(
            cloneNode(this._not_),
            cloneNode(this._expression4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotExpression4(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PExpression4 getExpression4()
    {
        return this._expression4_;
    }

    public void setExpression4(PExpression4 node)
    {
        if(this._expression4_ != null)
        {
            this._expression4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._expression4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._expression4_ == child)
        {
            this._expression4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._expression4_ == oldChild)
        {
            setExpression4((PExpression4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
