/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANotBoolfactor extends PBoolfactor
{
    private TNot _not_;
    private PBoolfactor _boolfactor_;

    public ANotBoolfactor()
    {
        // Constructor
    }

    public ANotBoolfactor(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PBoolfactor _boolfactor_)
    {
        // Constructor
        setNot(_not_);

        setBoolfactor(_boolfactor_);

    }

    @Override
    public Object clone()
    {
        return new ANotBoolfactor(
            cloneNode(this._not_),
            cloneNode(this._boolfactor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotBoolfactor(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PBoolfactor getBoolfactor()
    {
        return this._boolfactor_;
    }

    public void setBoolfactor(PBoolfactor node)
    {
        if(this._boolfactor_ != null)
        {
            this._boolfactor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._boolfactor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._boolfactor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._boolfactor_ == child)
        {
            this._boolfactor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._boolfactor_ == oldChild)
        {
            setBoolfactor((PBoolfactor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
