/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AStart extends PStart
{
    private TProgram _program_;
    private TIdentifier _identifier_;
    private TSemicolon _semicolon_;
    private TBegin _begin_;
    private final LinkedList<PDeclarations> _declarations_ = new LinkedList<PDeclarations>();
    private final LinkedList<PStatement> _statement_ = new LinkedList<PStatement>();
    private TProgramend _programend_;

    public AStart()
    {
        // Constructor
    }

    public AStart(
        @SuppressWarnings("hiding") TProgram _program_,
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_,
        @SuppressWarnings("hiding") TBegin _begin_,
        @SuppressWarnings("hiding") List<?> _declarations_,
        @SuppressWarnings("hiding") List<?> _statement_,
        @SuppressWarnings("hiding") TProgramend _programend_)
    {
        // Constructor
        setProgram(_program_);

        setIdentifier(_identifier_);

        setSemicolon(_semicolon_);

        setBegin(_begin_);

        setDeclarations(_declarations_);

        setStatement(_statement_);

        setProgramend(_programend_);

    }

    @Override
    public Object clone()
    {
        return new AStart(
            cloneNode(this._program_),
            cloneNode(this._identifier_),
            cloneNode(this._semicolon_),
            cloneNode(this._begin_),
            cloneList(this._declarations_),
            cloneList(this._statement_),
            cloneNode(this._programend_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStart(this);
    }

    public TProgram getProgram()
    {
        return this._program_;
    }

    public void setProgram(TProgram node)
    {
        if(this._program_ != null)
        {
            this._program_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._program_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    public TBegin getBegin()
    {
        return this._begin_;
    }

    public void setBegin(TBegin node)
    {
        if(this._begin_ != null)
        {
            this._begin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._begin_ = node;
    }

    public LinkedList<PDeclarations> getDeclarations()
    {
        return this._declarations_;
    }

    public void setDeclarations(List<?> list)
    {
        for(PDeclarations e : this._declarations_)
        {
            e.parent(null);
        }
        this._declarations_.clear();

        for(Object obj_e : list)
        {
            PDeclarations e = (PDeclarations) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._declarations_.add(e);
        }
    }

    public LinkedList<PStatement> getStatement()
    {
        return this._statement_;
    }

    public void setStatement(List<?> list)
    {
        for(PStatement e : this._statement_)
        {
            e.parent(null);
        }
        this._statement_.clear();

        for(Object obj_e : list)
        {
            PStatement e = (PStatement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._statement_.add(e);
        }
    }

    public TProgramend getProgramend()
    {
        return this._programend_;
    }

    public void setProgramend(TProgramend node)
    {
        if(this._programend_ != null)
        {
            this._programend_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programend_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._program_)
            + toString(this._identifier_)
            + toString(this._semicolon_)
            + toString(this._begin_)
            + toString(this._declarations_)
            + toString(this._statement_)
            + toString(this._programend_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._program_ == child)
        {
            this._program_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        if(this._begin_ == child)
        {
            this._begin_ = null;
            return;
        }

        if(this._declarations_.remove(child))
        {
            return;
        }

        if(this._statement_.remove(child))
        {
            return;
        }

        if(this._programend_ == child)
        {
            this._programend_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._program_ == oldChild)
        {
            setProgram((TProgram) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        if(this._begin_ == oldChild)
        {
            setBegin((TBegin) newChild);
            return;
        }

        for(ListIterator<PDeclarations> i = this._declarations_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclarations) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PStatement> i = this._statement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._programend_ == oldChild)
        {
            setProgramend((TProgramend) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
