/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AWhileOperation extends POperation
{
    private PWhileexpr _whileexpr_;

    public AWhileOperation()
    {
        // Constructor
    }

    public AWhileOperation(
        @SuppressWarnings("hiding") PWhileexpr _whileexpr_)
    {
        // Constructor
        setWhileexpr(_whileexpr_);

    }

    @Override
    public Object clone()
    {
        return new AWhileOperation(
            cloneNode(this._whileexpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileOperation(this);
    }

    public PWhileexpr getWhileexpr()
    {
        return this._whileexpr_;
    }

    public void setWhileexpr(PWhileexpr node)
    {
        if(this._whileexpr_ != null)
        {
            this._whileexpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whileexpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whileexpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whileexpr_ == child)
        {
            this._whileexpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whileexpr_ == oldChild)
        {
            setWhileexpr((PWhileexpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
