/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TNe extends Token
{
    public TNe()
    {
        super.setText("<>");
    }

    public TNe(int line, int pos)
    {
        super.setText("<>");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNe text.");
    }
}
